### ISSUE TITLE
Меню - не отображается логотип

### ISSUE THREAD

**Issue by imboogieman** [imboogieman/OuterNET#1]
![logo_bug_01](https://cloud.githubusercontent.com/assets/16269033/25585875/544406b8-2ea5-11e7-9c80-b7a31815e438.png)

**Comment by romanbolshakov** [comment]
Подставил логотип "Garson". В ресурсах проекта нет логотипов ресторанов (bristle, park). Пришлите, по возможности.

**Comment by imboogieman** [comment]
@romanbolshakov Дал доступ на папку Гугл Драйв с логотипами.

**Comment by romanbolshakov** [comment]
@imboogieman обновил иконки (лого)
