### ISSUE TITLE
Админка - переименовать кнопку

### ISSUE THREAD

**Issue by imboogieman** [imboogieman/OuterNET#3]
Если пользователь отменяет заказ, заказ получает статус "Отменён", на карточке должна появиться кнопка "Восстановить", вместо "Новый". 
![status_sequence_02](https://cloud.githubusercontent.com/assets/16269033/25586208/091b4e6a-2ea7-11e7-9129-e5a7bf109e43.png)

**Comment by romanbolshakov** [comment]
fixed
