### ISSUE TITLE
Меню - не отображается на Сафари

### ISSUE THREAD

**Issue by imboogieman** [imboogieman/OuterNET#4]
После загрузки сайта через мобильный браузер Сафари, содержание не отображается.
Это критично, т.к. мобильный Сафари достаточно полярен. Если работа по устранению бага достаточно трудоёмкая (более 8 часов), то можно отложить.

**Comment by romanbolshakov** [comment]
Я проверю в чем может быть причина

**Comment by romanbolshakov** [comment]
Fix. Check it please

**Comment by imboogieman** [comment]
@romanbolshakov 
Тестируем на роутерах. На сафари снова не отображается контент в окне браузера.

**Comment by romanbolshakov** [comment]
Не видно меню? Заголовок с категориями (салаты, закуски и пр.) отображается?

**Comment by imboogieman** [comment]
@romanbolshakov страница пустая - белая.

**Comment by romanbolshakov** [comment]
@imboogieman проверил на iOS 9.3 (safari) bristle.garson.pro отображается. Есть проблема с фиксированным заголовком (с категориями): он занимает почти весь экран, но это другая проблема. На каком устройстве не отображается?
