### ISSUE TITLE
Не отображается или не подгружается контент 

### ISSUE THREAD

**Issue by imboogieman** [imboogieman/OuterNET#5]
Устройства Android
Браузер: Chrome

![screenshot_2017-05-25-17-48-09](https://cloud.githubusercontent.com/assets/16269033/26456638/61cd3834-4176-11e7-9bca-c181c8a7194d.png)
![screenshot_2017-05-25-17-52-18](https://cloud.githubusercontent.com/assets/16269033/26456643/63eb6bc2-4176-11e7-81b8-59db55377ae5.png)

**Comment by imboogieman** [comment]
@romanbolshakov  При тестировании не отображался контент меню для точки Bristle
Периодически на меню других точек подгружается после обновления страницы.

**Comment by romanbolshakov** [comment]
@imboogieman Сейчас контент доступен для всех 3-х точек. Полагаю, что проблема может быть связана с протоколом http (сейчас работаем только с https). Сделаю переадресацию с http на https

**Comment by romanbolshakov** [comment]
@imboogieman на Android'e garson открывается корректно 
![1f762szvwie](https://user-images.githubusercontent.com/3818095/28455798-933580f0-6e00-11e7-9e1e-edf2afce9c2b.jpg)

**Comment by imboogieman** [comment]
@romanbolshakov , вероятно, проблема вызвана была при заходе через роутер. Эту проблему мы и будем обсуждать на следующем созвоне. Пока закрываю.
