### ISSUE TITLE
Admin - Push - неверная ссылка переадресации

### ISSUE THREAD

**Issue by imboogieman** [imboogieman/OuterNET#8]
**Воспроизведение:**
Клиент оформляет заказ
Клиент отправляет заказ
Система принимает заказ
Система оповещает админа о новом заказе
Админ кликает на оповещение
**_Происходит передаресация на страницу с меню заведения_ (Неправильно)**

**Правильно:** Происходит переадресация на страницу админки

**Comment by romanbolshakov** [comment]
@imboogieman исправлено
